version: "2"
services:
    googletest:
        build:
            context: .
            dockerfile: "Dockerfile"
        volumes:
            - "./code:/code"
        working_dir: "/code"
        entrypoint:
            - "googletest"